### ISSUE TITLE
Regarding Translation To Intermediate Code(chap7)

### ISSUE THREAD

**Issue by PrajwalaTM** [dengwanc/Tiger#3]
The makefile with "ctags -R *" gives an error saying 
command:ctags not found
On removal of ctags, no output is being generated for most of the testcases. A few of them give an output saying "fragList is null". Can you please look into this ? Thank you.

**Comment by dengwanc** [comment]
I'am Sorry.
Recently I have no time to Review this，Because I'm So Busy. 
You could Ask https://github.com/AssemblyCoffee.

**Comment by dengwanc** [comment]
# 项目启动

* `npm i -g typescript nodemon`
* `npm i`
* `tsc -w`
* `npm run dev`

# 术语

* Dish // 菜品
* Combo // 套餐

# 页面组件划分

### 通用组件

* loading 组件
* 全局悬浮组件

### 未开启自助点餐页面

### 点餐页面

* 未开启接单设备提示组件
    * 提示信息
    * 禁用所有点餐按钮

* header
    * back
    * title
    * serach

* menu
    * cate_list(滚动
        * cate item
    * 待选菜品list
        * 菜品 item
            * header(<10字)
                * title
                * tags [起售/剩余]
            * price
                * number
                * limmit(optional)
            * 计数器／选择／不可售
* footer
    * cart
        * 清空购物车
        * 已点列表
            * 已点条目
                * detail_header @计算属性
                * computed price
                * 计数器／称重器
                * description @optional
    * 选好了

* 规格菜品组件
* 套餐组件
* 称重菜组件

###  确认订单页面

* 添加备注
    * 限制字数输入组件
    * 完成
* 下单

### 支付订单页面

* 确认支付

### 支付成功页面
### 支付失败页面

# 本周目标

* 环境搭建完成，保证下周可以直接上手开发
* 组件划分

# PM 需求

* 多规格点餐交互问题
* 购物车分类标题不做
* 确认订单页面点菜功能，待讨论
