### ISSUE TITLE
Bison warning: shift/reduce conflicts

### ISSUE THREAD

**Issue by xjiajiahao** [dengwanc/Tiger#4]
When I used bison to generate C code, I met with a warning:
```
tiger.y: warning: 64 shift/reduce conflicts [-Wconflicts-sr]
```
Does this warning matter?

**Comment by dengwanc** [comment]
It's OK;

文法可能有产生冲突。
我记得有优先级可以设置，你可以研究一下 bison 的用法

**Comment by xjiajiahao** [comment]
OK，谢啦！
